### PR TITLE
fix: ensure fully qualified URL recorded for auditing

### LINKED ISSUE #141: Audit log URLs are incomplete
I'm seeing the audit logs recorded by boundary seem to only have the path portion of the URL rather than a fully qualified URL. The application logs also seem to suffer from the same problem.

Application log example (from `/tmp/boundary_logs/...` on dogfood):
`time=2026-01-06T15:51:12.123Z level=WARN msg=DENY method=POST url=/api/api_post.php host=pastebin.com`
I think the `url` field should be `url=https://pastebin.com/api/api_post.php`

Audit log example from coderd logs for allowed request:
`2026-01-06 15:50:31.267 [info]  coderd.agentrpc: boundary_request  trace=c4d6a7aaf78a5c232a9fe76ee93f2c6a  span=2def2b54ab24ce2f  owner=zachkipp  workspace_name=upload-source-pastebin-bb0d  agent_name=dev  decision=allow  workspace_id=b21d26f6-b45e-4d3d-b1b9-9ac9a7403626  http_method=GET  http_url=/lookup/github.com/modelcontextprotocol/go-sdk@v0.8.0  event_time=2026-01-06T15:50:31.252989316Z  matched_rule=domain=[sum.golang.org](http://sum.golang.org/)  request_id=dfaf838f-37c7-4941-b5db-442ca000b797`

Audit log example from coderd logs for denied request:
`2026-01-06 15:50:38.865 [info]  coderd.agentrpc: boundary_request  trace=c4d6a7aaf78a5c232a9fe76ee93f2c6a  span=2def2b54ab24ce2f  owner=zachkipp  workspace_name=upload-source-pastebin-bb0d  agent_name=dev  decision=deny  workspace_id=b21d26f6-b45e-4d3d-b1b9-9ac9a7403626  http_method=POST  http_url=/api/v2/logs  event_time=2026-01-06T15:50:37.259073861Z  request_id=dfaf838f-37c7-4941-b5db-442ca000b797`

Relates to https://github.com/coder/coder/issues/21280

### PR DESCRIPTION
**Pull request by zedkipp**
Previously the audit URL only contained the path (e.g., "/lookup/github.com/...") for HTTPS requests via CONNECT tunnel, instead of the full URL with scheme and host (e.g., `"https://sum.golang.org/lookup/github.com/..."`).

For example, the application logs look like this `time=2026-01-06T15:51:12.123Z level=WARN msg=DENY method=POST url=/api/api_post.php host=pastebin.com`. The `url` field should be `url=https://pastebin.com/api/api_post.php`.

This happened because http.ReadRequest() only populates req.URL with the path when parsing requests inside a TLS tunnel. The fix checks if req.URL.Scheme is empty and prepends the scheme and host when needed. A single URL is constructed for use with the rules engine and auditing purposes.

Fixes #141

### CODE REVIEW

File: audit/request.go [hunk 1]
```diff
@@ -7,7 +7,7 @@ type Auditor interface {
 // Request represents information about an HTTP request for auditing
 type Request struct {
 	Method  string
-	URL     string
+	URL     string // The fully qualified request URL (scheme, domain, optional path).
 	Host    string
```
Comment (zedkipp) [inline audit/request.go]: Including the host here seems redundant if the URL is fully qualified. Should we remove it?

Comment (evgeniy-scherbina) [reply audit/request.go]: I think for analyzing logs and building dashboards based on logs - it will be easier to have structured logs:
- scheme
- domain
- path
- query_params
?

Probably we'll want to run some aggregations queries based on domain? It may be harder to run aggregations queries if we only have string with fully qualified URL?

File: proxy/proxy.go [hunk 2]
```diff
@@ -261,13 +261,25 @@ func (p *Server) processHTTPRequest(conn net.Conn, req *http.Request, https bool
 	p.logger.Debug("   Host", "host", req.Host)
 	p.logger.Debug("   User-Agent", "user-agent", req.Header.Get("User-Agent"))
 
-	// Check if request should be allowed
-	result := p.ruleEngine.Evaluate(req.Method, req.Host+req.URL.String())
+	// For HTTP proxy requests, req.URL contains the full URL.
+	// For HTTPS via CONNECT tunnel, req.URL only contains the path.
+	evalURL := req.URL.String()
+	if req.URL.Scheme == "" {
```
Comment (evgeniy-scherbina) [inline proxy/proxy.go]: Should we check that `req.URL.Scheme` is empty or `req.URL.Host` is empty?

File: audit/request.go (hunk 1 above)
Comment (zedkipp) [reply audit/request.go]: For now I'm inclined to just make this the fully-qualified URL so that the application logs are accurate and the consumers actually get the full URL. Consumers can parse it, if desired.

That said, I think it would make sense to ultimately structure the logs a bit better in coder. I'll see how things pan out after dogfooding for a bit.
